<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-01T07:23:55 IST" name="Suite" finished-at="2024-04-01T07:24:42 IST" duration-ms="46896">
    <groups>
    </groups>
    <test started-at="2024-04-01T07:23:55 IST" name="Test" finished-at="2024-04-01T07:24:42 IST" duration-ms="46896">
      <class name="com.quafox.tests.Login">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:23:56 IST" name="setup" finished-at="2024-04-01T07:24:04 IST" duration-ms="8258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithValidCredentials()[pri:1, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:04 IST" name="verifyLoginWithValidCredentials" finished-at="2024-04-01T07:24:06 IST" duration-ms="1778" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:06 IST" name="tearDown" finished-at="2024-04-01T07:24:06 IST" duration-ms="548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:06 IST" name="setup" finished-at="2024-04-01T07:24:13 IST" duration-ms="6507" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithInvalidCredentials()[pri:2, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:13 IST" name="verifyLoginWithInvalidCredentials" finished-at="2024-04-01T07:24:24 IST" duration-ms="11473" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:24 IST" name="tearDown" finished-at="2024-04-01T07:24:25 IST" duration-ms="541" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:25 IST" name="setup" finished-at="2024-04-01T07:24:31 IST" duration-ms="5776" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithInvalidUsername()[pri:3, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:31 IST" name="verifyLoginWithInvalidUsername" finished-at="2024-04-01T07:24:32 IST" duration-ms="1514" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidUsername -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:32 IST" name="tearDown" finished-at="2024-04-01T07:24:33 IST" duration-ms="535" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:33 IST" name="setup" finished-at="2024-04-01T07:24:40 IST" duration-ms="6740" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithInvalidPassword()[pri:4, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:40 IST" name="verifyLoginWithInvalidPassword" finished-at="2024-04-01T07:24:41 IST" duration-ms="1390" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.quafox.tests.Login.verifyLoginWithInvalidPassword(Login.java:97)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.quafox.tests.Login@5d0bf09b]" started-at="2024-04-01T07:24:41 IST" name="tearDown" finished-at="2024-04-01T07:24:42 IST" duration-ms="490" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.quafox.tests.Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
